### ISSUE TITLE
Error when build on ubuntu 14.04

### ISSUE THREAD

**Issue by thelinh** [falvaro/seshat#8]
Hi all,

I built seshat success on centos 6.7 (32 bit) use gcc version 4.4.7, boost 1_54_0, xerces-c-3.1.3.

Now I try to build seshat on ubuntu 14.04 (64 bit).
I use the same dependency on centos 6.7.
I installed gcc version 4.4.7. Use boost 1_54_0 and  xerces-c-3.1.3.

But i face below error.

g++ -c sample.cc -O3 -Wno-unused-result -I/home/thelinh/work_space/math_ocr/tool_for_seshat/boost_1_54_0/
In file included from /usr/local/include/xercesc/util/Xerces_autoconf_config.hpp:88,
                 from /usr/local/include/xercesc/util/XercesDefs.hpp:46,
                 from /usr/local/include/xercesc/util/PlatformUtils.hpp:25,
                 from sample.cc:31:
/usr/include/inttypes.h:290: error: reference to ‘intmax_t’ is ambiguous
/usr/include/stdint.h:134: error: candidates are: typedef long int intmax_t
/home/thelinh/work_space/math_ocr/tool_for_seshat/boost_1_54_0/boost/cstdint.hpp:306: error:                 typedef boost::long_long_type boost::intmax_t
/usr/include/inttypes.h:290: error: reference to ‘intmax_t’ is ambiguous
/usr/include/stdint.h:134: error: candidates are: typedef long int intmax_t
/home/thelinh/work_space/math_ocr/tool_for_seshat/boost_1_54_0/boost/cstdint.hpp:306: error:                 typedef boost::long_long_type boost::intmax_t
/usr/include/inttypes.h:290: error: ‘intmax_t’ does not name a type
/usr/include/inttypes.h:293: error: reference to ‘intmax_t’ is ambiguous
/usr/include/stdint.h:134: error: candidates are: typedef long int intmax_t
/home/thelinh/work_space/math_ocr/tool_for_seshat/boost_1_54_0/boost/cstdint.hpp:306: error:                 typedef boost::long_long_type boost::intmax_t
/usr/include/inttypes.h:293: error: reference to ‘intmax_t’ is ambiguous
/usr/include/stdint.h:134: error: candidates are: typedef long int intmax_t
/home/thelinh/work_space/math_ocr/tool_for_seshat/boost_1_54_0/boost/cstdint.hpp:306: error:                 typedef boost::long_long_type boost::intmax_t
/usr/include/inttypes.h:293: error: reference to ‘intmax_t’ is ambiguous

...

Attacked file is output result when i run make.
[results.txt](https://github.com/falvaro/seshat/files/320997/results.txt)

Please help me.
